"""add document status and created_at

Revision ID: 5c57dd0f79c4
Revises: 687f769e3c3e
Create Date: 2026-10-04 06:13:30.501542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c57dd0f79c4'
down_revision: Union[str, Sequence[str], None] = '687f769e3c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('status', sa.String(length=255), server_default= "uploaded", nullable=False))
    op.add_column('document', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'created_at')
    op.drop_column('document', 'status')
    # ### end Alembic commands ###
