"""add docuemnt storage path

Revision ID: 926343da9b5f
Revises: 5c57dd0f79c4
Create Date: 2026-10-05 20:49:00.795386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '926343da9b5f'
down_revision: Union[str, Sequence[str], None] = '5c57dd0f79c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('storage_path', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'storage_path')
    # ### end Alembic commands ###
