"""add unique constraint to document chunks

Revision ID: b4e1e82d7170
Revises: 7487c890fea3
Create Date: 2026-10-05 23:58:53.417631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4e1e82d7170'
down_revision: Union[str, Sequence[str], None] = '7487c890fea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_document_chunk_document_id_chunk_index', 'document_chunk', ['document_id', 'chunk_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_document_chunk_document_id_chunk_index', 'document_chunk', type_='unique')
    # ### end Alembic commands ###
