"""add embeddings to document chunks

Revision ID: feb653d7d292
Revises: b4e1e82d7170
Create Date: 2026-10-06 17:01:21.385876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'feb653d7d292'
down_revision: Union[str, Sequence[str], None] = 'b4e1e82d7170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunk', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunk', 'embedding')
    # ### end Alembic commands ###
